force-app/main/default/objects/Mcoe_Service_Requests__c/Mcoe_Service_Requests__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mcoe_Service_Requests__c/fields/Mcoe_New_Sandbox_Description__c.field-meta.xml
<CustomField>
    <fullName>Mcoe_New_Sandbox_Description__c</fullName>
    <description>This field hold description of the requested sandbox.</description>
    <label>New Sandbox Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Mcoe_Service_Requests__c/fields/Mcoe_Prod_Sandbox_Names__c.field-meta.xml
<CustomField>
    <fullName>Mcoe_Prod_Sandbox_Names__c</fullName>
    <label>Prod Sandbox Names</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NewSandboxes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mcoe_Service_Requests__c/fields/Mcoe_Request_Priority__c.field-meta.xml
<CustomField>
    <fullName>Mcoe_Request_Priority__c</fullName>
    <description>This field will have priority of service request</description>
    <label>Request Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Urgent</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
                <default>true</default>
                <label>Medium</label>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mcoe_Service_Requests__c/fields/Mcoe_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Mcoe_Request_Status__c</fullName>
    <description>This field will have status of the service request</description>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Sent for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Failed to process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mcoe_Service_Requests__c/fields/Mcoe_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Mcoe_Request_Type__c</fullName>
    <description>This field will have information of requested operation like Create, Refresh or delete sandbox</description>
    <label>Request Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Create New Sandbox</fullName>
            </value>
            <value>
                <fullName>Refresh Existing Sandbox</fullName>
            </value>
            <value>
                <fullName>Delete Existing Sandbox</fullName>
            </value>
            <value>
                <fullName>Create&quot;</fullName>
                <isActive>false</isActive>
                <label>Create&quot;</label>
            </value>
            <value>
                <fullName>Delete</fullName>
                <isActive>false</isActive>
                <label>Delete</label>
            </value>
            <value>
                <fullName>Refresh</fullName>
                <isActive>false</isActive>
                <label>Refresh</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mcoe_Service_Requests__c/fields/Mcoe_Requestor__c.field-meta.xml
<CustomField>
    <fullName>Mcoe_Requestor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field will have requestor information</description>
    <label>Requestor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Service_Requests7</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mcoe_Service_Requests__c/fields/Mcoe_Sandbox_Name__c.field-meta.xml
<CustomField>
    <fullName>Mcoe_Sandbox_Name__c</fullName>
    <description>This field will hold requested new Sandbox Name</description>
    <label>Sandbox Name</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mcoe_Service_Requests__c/fields/Mcoe_Sandbox_Type__c.field-meta.xml
<CustomField>
    <fullName>Mcoe_Sandbox_Type__c</fullName>
    <description>This field will have requested sandbox type.</description>
    <label>Sandbox Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Developer Pro</fullName>
            </value>
            <value>
                <fullName>Partial Copy</fullName>
            </value>
            <value>
                <fullName>Full Copy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/NewSandboxes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>refresh</fullName>
    </customValue>
    <customValue>
        <fullName>devenv</fullName>
    </customValue>
    <customValue>
        <fullName>sample</fullName>
    </customValue>
    <customValue>
        <fullName>lwcSandbox</fullName>
    </customValue>
    <customValue>
        <fullName>ootb1</fullName>
    </customValue>
    <customValue>
        <fullName>ni</fullName>
    </customValue>
    <customValue>
        <fullName>finaltest</fullName>
    </customValue>
    <customValue>
        <fullName>26te</fullName>
    </customValue>
    <customValue>
        <fullName>final</fullName>
    </customValue>
    <customValue>
        <fullName>26test1</fullName>
    </customValue>
    <customValue>
        <fullName>26test5</fullName>
    </customValue>
    <customValue>
        <fullName>ni26test</fullName>
    </customValue>
    <customValue>
        <fullName>ni26test2</fullName>
    </customValue>
    <customValue>
        <fullName>ootb2</fullName>
    </customValue>
    <customValue>
        <fullName>ootb3</fullName>
    </customValue>
    <customValue>
        <fullName>devenv1</fullName>
    </customValue>
    <customValue>
        <fullName>testing</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
        <isActive>false</isActive>
        <label>None</label>
    </customValue>
    <masterLabel>NewSandboxes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Mcoe_SRA_ToolingAPI_Test.cls
@isTest
public class Mcoe_SRA_ToolingAPI_Test {
    @isTest
    static void testProcessServiceRequest(){
        Contact newContact = new Contact(LastName='Test User');
        Insert newContact;
        Mcoe_Service_Requests__c createSandboxSuccess = new Mcoe_Service_Requests__c(Mcoe_Requestor__c = newContact.Id, Mcoe_Request_Type__c = 'Create New Sandbox', Mcoe_Sandbox_Name__c = 'CreateScs', Mcoe_Request_Status__c = 'Approved', Mcoe_Request_Priority__c = 'Medium', Mcoe_New_Sandbox_Description__c = 'Create New Sandbox Success', Mcoe_Sandbox_Type__c = 'Developer');
        Mcoe_Service_Requests__c refreshSandboxSuccess = new Mcoe_Service_Requests__c(Mcoe_Requestor__c = newContact.Id, Mcoe_Request_Type__c = 'Refresh Existing Sandbox', Mcoe_Prod_Sandbox_Names__c = '26te', Mcoe_Request_Status__c = 'Approved', Mcoe_Request_Priority__c = 'Medium', Mcoe_Sandbox_Type__c = 'Developer');
        Mcoe_Service_Requests__c deleteSandboxSuccess = new Mcoe_Service_Requests__c(Mcoe_Requestor__c = newContact.Id, Mcoe_Request_Type__c = 'Delete Existing Sandbox', Mcoe_Prod_Sandbox_Names__c = '26te', Mcoe_Request_Status__c = 'Approved', Mcoe_Request_Priority__c = 'Medium');
        List<Mcoe_Service_Requests__c> listofsr=new List<Mcoe_Service_Requests__c>();
        listofsr.add(createSandboxSuccess);
        listofsr.add(refreshSandboxSuccess);
        listofsr.add(deleteSandboxSuccess);
        insert listofsr;
        Test.startTest();
        Mcoe_SRA_ToolingAPI.processServiceRequest(listofsr);
        Test.StopTest();
    }
}